---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - instance.neovim.prot0s.com
  resources:
  - neovims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instance.neovim.prot0s.com
  resources:
  - neovims/finalizers
  verbs:
  - update
- apiGroups:
  - instance.neovim.prot0s.com
  resources:
  - neovims/status
  verbs:
  - get
  - patch
  - update
